language: node_js
node_js:
  - "6"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
jobs:
  include:
    - stage: lint
    - stage: test
    - stage: build